# Generated by Django 6.0.2 on 2026-02-11 18:35

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isbn_number', models.CharField(max_length=20, unique=True, validators=[books.validators.validate_isbn])),
                ('genre', models.CharField(choices=[('FA', 'FANTASY'), ('SCI', 'SCI_FI'), ('RO', 'ROMANCE'), ('MY', 'MYSTERY'), ('THR', 'THRILLER'), ('HO', 'HORROR'), ('HH', 'HISTORICAL'), ('LI', 'LITERARY'), ('BG', 'BIOGRAPHY'), ('SC', 'SCIENCE'), ('CR', 'CRIME'), ('OT', 'OTHER')], max_length=30)),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
